import 'dotenv/config';

const {
  BRAND_FISHER_PRICE,
  BRAND_PREMIUM_BABY,
  BRAND_CARESTINO,
  BRAND_CARTERS,
  BRAND_SANCORD,
  STORE_CEBRA,
  STORE_BABYNET,
  STORE_SANCORD,
  SOTRE_BUKITO,
  LOCATION,
  ITEM_CONDITION_NEW
} = process.env;

export const STATE = LOCATION;
export const ITEM_CONDITION = ITEM_CONDITION_NEW;
export const LIMIT_ITEMS = 10;
export const HAS_PICTURES = 'yes';
export const BRANDS = [
  BRAND_FISHER_PRICE,
  BRAND_PREMIUM_BABY,
  BRAND_CARESTINO,
  BRAND_CARTERS,
  BRAND_SANCORD,
];
export const STORES = [
  STORE_CEBRA,
  STORE_BABYNET,
  STORE_SANCORD,
  SOTRE_BUKITO,
];


